FROM mariadb:latest

ENV MYSQL_DATABASE=SAMPLE_DB

ENV MYSQL_ROOT_PASSWORD=1234

# Set the default character set and collation for the custom database
ENV MYSQL_CHARSET=utf8
ENV MYSQL_COLLATION=utf8_general_ci

# Expose the default MariaDB port
EXPOSE 3306